<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKdUGUVQ\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKdUGUVQ/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerKdUGUVQ.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerKdUGUVQ\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerKdUGUVQ\App_KernelProdContainer([
    'container.build_hash' => 'KdUGUVQ',
    'container.build_id' => 'f775fbff',
    'container.build_time' => 1786551384,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKdUGUVQ');
