<?php

namespace ContainerKdUGUVQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OuTyNwService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator._ouTyNw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._ouTyNw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formule' => ['privates', '.errored..service_locator._ouTyNw.App\\Entity\\FormulePromoReseau', NULL, 'Cannot autowire service ".service_locator._ouTyNw": it references class "App\\Entity\\FormulePromoReseau" but no such service exists.'],
        ], [
            'formule' => 'App\\Entity\\FormulePromoReseau',
        ]);
    }
}
