<?php

namespace ContainerKdUGUVQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EbasS8oService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ebasS8o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ebasS8o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'formulePromoAffaireRepository' => ['privates', 'App\\Repository\\FormulePromoAffaireRepository', 'getFormulePromoAffaireRepositoryService', true],
            'promotion' => ['privates', '.errored..service_locator.ebasS8o.App\\Entity\\Promotion', NULL, 'Cannot autowire service ".service_locator.ebasS8o": it references class "App\\Entity\\Promotion" but no such service exists.'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'entityManager' => '?',
            'formulePromoAffaireRepository' => 'App\\Repository\\FormulePromoAffaireRepository',
            'promotion' => 'App\\Entity\\Promotion',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
