<?php

namespace ContainerKdUGUVQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormulePromoReseau3Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator._ouTyNw.App\Entity\FormulePromoReseau' shared service.
     *
     * @return \App\Entity\FormulePromoReseau
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator._ouTyNw": it references class "App\\Entity\\FormulePromoReseau" but no such service exists.');
    }
}
