<?php

namespace ContainerKdUGUVQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPublicSocialNetworkCatalogControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\API\PublicSocialNetworkCatalogController' shared autowired service.
     *
     * @return \App\Controller\API\PublicSocialNetworkCatalogController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\API\\PublicSocialNetworkCatalogController'] = $instance = new \App\Controller\API\PublicSocialNetworkCatalogController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\API\\PublicSocialNetworkCatalogController', $container));

        return $instance;
    }
}
