<?php

namespace ContainerKdUGUVQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromotion5Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.ebasS8o.App\Entity\Promotion' shared service.
     *
     * @return \App\Entity\Promotion
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ebasS8o": it references class "App\\Entity\\Promotion" but no such service exists.');
    }
}
